### ISSUE TITLE
Errors during "Generate animation frames"

### ISSUE THREAD

**Issue by VicRejkia** [dmarx/video-killed-the-radio-star#94] opened 2022-12-08 22:57 UTC
Everything worked fine till i got to the Generate animation frames part.
It stopped on the fetching variations at this loop:
`for _ in range(tot_variations):`

```
Fetching variations
1
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-12-ccdc85f3c37d>](https://localhost:8080/#) in <module>
    153         tot_variations -= curr_variation_count  # only generate variations we still need
    154         for _ in range(tot_variations):
--> 155             img = get_variations_w_init(prompt, init_image, start_schedule=(1-image_consistency))[0]
    156             save_frame(
    157                 img,

3 frames
[/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py](https://localhost:8080/#) in decorate_context(*args, **kwargs)
     25         def decorate_context(*args, **kwargs):
     26             with self.clone():
---> 27                 return func(*args, **kwargs)
     28         return cast(F, decorate_context)
     29 

TypeError: __call__() missing 1 required positional argument: 'image'
```

**Comment by dmarx** [comment] 2022-12-30 00:40
i'm wondering if maybe this was a bug due to a change in huggingface or something like that? I swear I was able to reproduce this not that long ago, but now I can't. Can you double check if this is still an issue for you?

**Comment by SchmitzAndrew** [comment] 2023-03-04 00:38
I got a very similar issue today.  I was able to reproduce it after reloading the notebook and rerunning everything.
```
Fetching variations
1
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-20-6970025e684d>](https://localhost:8080/#) in <module>
    153         tot_variations -= curr_variation_count  # only generate variations we still need
    154         for _ in range(tot_variations):
--> 155             img = get_variations_w_init(prompt, init_image, start_schedule=(1-image_consistency))[0]
    156             save_frame(
    157                 img,

3 frames
[/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py](https://localhost:8080/#) in decorate_context(*args, **kwargs)
     25         def decorate_context(*args, **kwargs):
     26             with self.clone():
---> 27                 return func(*args, **kwargs)
     28         return cast(F, decorate_context)
     29 

TypeError: __call__() got an unexpected keyword argument 'init_image'
```

**Comment by mjea1980** [comment] 2023-03-04 17:06
> I got a very similar issue today. I was able to reproduce it after reloading the notebook and rerunning everything.
> 
> ```
> Fetching variations
> 1
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> [<ipython-input-20-6970025e684d>](https://localhost:8080/#) in <module>
>     153         tot_variations -= curr_variation_count  # only generate variations we still need
>     154         for _ in range(tot_variations):
> --> 155             img = get_variations_w_init(prompt, init_image, start_schedule=(1-image_consistency))[0]
>     156             save_frame(
>     157                 img,
> 
> 3 frames
> [/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py](https://localhost:8080/#) in decorate_context(*args, **kwargs)
>      25         def decorate_context(*args, **kwargs):
>      26             with self.clone():
> ---> 27                 return func(*args, **kwargs)
>      28         return cast(F, decorate_context)
>      29 
> 
> TypeError: __call__() got an unexpected keyword argument 'init_image'
> ```

Hey Andrew,  I'm having this issue as well.  Were you able to find a solution?

**Comment by SchmitzAndrew** [comment] 2023-03-05 00:58
Unfortunately not. I've been able to generate videos in the past so I'm not sure what the cause is. Please let me know if you come up with anything.

**Comment by mjea1980** [comment] 2023-03-05 13:10
Same with me.  I had no issues 2 days ago,  then yesterday that issue popped up.  Hopefully it just kind of fixes itself. lol

**Comment by SchmitzAndrew** [comment] 2023-03-06 00:04
@mjea1980 ,

I tried the solution proposed in https://github.com/dmarx/video-killed-the-radio-star/pull/96 but wasn't able to get it to work.  Might be worth a shot.

**Comment by mjea1980** [comment] 2023-03-07 00:34
@H2whoaMusic @SchmitzAndrew I tried to put together a video this morning,  and still no dice.  Its generates such cool images,  I wish it would just finish off the final step!! haha.  Hopefully one day soon it starts working again :)

@dmarx any idea what the problem could be ?  Looks like its been a known issue for a couple months now..

**Comment by H2whoaMusic** [comment] 2023-03-07 13:37
@mjea1980 I know, I'm in the same boat. I've generated some truly fantastic images. @dmarx was kind enough to guide me on how to modify the storyboard to make really bespoke sequences, and I'm dying to get it pulled together!

**Comment by ianhirsch** [comment] 2023-03-07 19:16
I'm getting the same issue and was able to create a video about a month ago! not sure what changed here

**Comment by DerisoryPull** [comment] 2023-03-07 22:04
Same issue here! That...was not a good timing to buy Colab pro

**Comment by H2whoaMusic** [comment] 2023-03-08 08:35
> Same issue here! That...was not a good timing to buy Colab pro

Lol, same. But I have faith that a solution will be found. It's way out of my very limited coding experience, but it's such an impressive project that I don't doubt that it will get resolved.

**Comment by dmarx** [comment] 2023-03-22 19:46
thanks for your patience folks and sorry for the delay, issue should be fixed now. Will close this after I've got confirmation from one of y'all that it's working for you as well.

@ianhirsch @DerisoryPull @H2whoaMusic @mjea1980 @SchmitzAndrew @VicRejkia

**Comment by ianhirsch** [comment] 2023-03-22 20:15
You’re the man! I’ll give it a go this afternoon and report back 🫡

**Comment by DerisoryPull** [comment] 2023-03-22 21:15
Lol My Colab pro expired a couple hours ago

**Comment by H2whoaMusic** [comment] 2023-03-22 22:38
So far, so good. Created a new project and taken it right through to generating animation images. Currently running and appears to be working. Actively generating images, which it was not doing before. Will confirm once completed, but looks good. Thank you!

**Comment by H2whoaMusic** [comment] 2023-03-22 23:05
I am now compiling my video! Was able to generate the animation frames successfully. Huge thanks to you, @dmarx

**Closed** 2023-03-22 23:23 UTC
Labels: bug
